{{- if .Values.ingress.enabled -}}
{{- $fullName := include "portfolio-orchestrator.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-display
  labels:
    {{- include "portfolio-orchestrator.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.useRegex }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /app/portfolio/display/$2
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ $.Values.ingress.host | quote }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ if .Values.ingress.useRegex }}/app/portfolio/display(/|$)(.*){{ else }}/app/portfolio/display{{ end }}
            pathType: {{ if .Values.ingress.useRegex }}ImplementationSpecific{{ else }}Prefix{{ end }}
            backend:
              service:
                name: {{ $fullName }}-display
                port:
                  name: display
{{- end }}
