apiVersion: v2
name: application-services
description: A Helm chart for deploying the Application Services Spring Boot microservice in Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"
